"""Initial commit

Revision ID: 6bb40c56a003
Revises: 
Create Date: 2025-08-22 14:04:05.642800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb40c56a003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_summary', sa.Text(), nullable=False),
    sa.Column('jd_keywords', sa.Text, nullable=False),
    sa.Column('jd_skills', sa.Text, nullable=False),
    sa.Column('jd_tasks', sa.Text, nullable=False),
    sa.Column('jd_technologies', sa.Text, nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_evaluations_content_hash'), 'jd_evaluations', ['content_hash'], unique=True)
    op.create_table('library_version',
    sa.Column('library_version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('library_version_id'),
    sa.UniqueConstraint('version_label')
    )
    op.create_table('jd_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at_utc', sa.DateTime(), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('process_name', sa.String(length=50), nullable=False),
    sa.Column('input_payload', sa.Text(), nullable=True),
    sa.Column('output_payload', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('env', sa.String(length=50), nullable=True),
    sa.Column('source_filename', sa.String(length=300), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('jd_evaluation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jd_evaluation_id'], ['jd_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('library_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('organization', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_version_id'], ['library_version.library_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('bp_decision_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('library_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_version_id'], ['library_version.library_version_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['jd_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bullet',
    sa.Column('bullet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bullet_id')
    )
    op.create_table('bp_decision_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_set_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['decision_set_id'], ['bp_decision_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_set_id', 'code', name='uq_decset_code')
    )
    op.create_table('bp_decision_bullets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_section_id', sa.Integer(), nullable=False),
    sa.Column('source_bullet_id', sa.Integer(), nullable=True),
    sa.Column('text_snapshot', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decision_section_id'], ['bp_decision_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_bullet_id'], ['bullet.bullet_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bp_decision_bullets')
    op.drop_table('bp_decision_sections')
    op.drop_table('bullet')
    op.drop_table('bp_decision_sets')
    op.drop_table('section')
    op.drop_table('jd_transactions')
    op.drop_table('library_version')
    op.drop_index(op.f('ix_jd_evaluations_content_hash'), table_name='jd_evaluations')
    op.drop_table('jd_evaluations')
    # ### end Alembic commands ###
