"""added organization to section table

Revision ID: 9e8a36ea897a
Revises: be169bf42678
Create Date: 2025-08-19 10:48:30.490274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8a36ea897a'
down_revision: Union[str, Sequence[str], None] = 'be169bf42678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('organization', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'organization')
    # ### end Alembic commands ###
