"""added title to section table

Revision ID: be169bf42678
Revises: bbf1fd57d045
Create Date: 2025-08-19 09:35:03.914643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be169bf42678'
down_revision: Union[str, Sequence[str], None] = 'bbf1fd57d045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'title')
    # ### end Alembic commands ###
